name: verify modelproj
on: [push]
jobs:
    verify-siriuschallenge-web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'npm'

            - name: Install dependencies
              working-directory: ./
              run: npm i

            - name: Typecheck
              working-directory: ./
              run: npm run typecheck

            - name: Lint
              working-directory: ./
              run: npm run lint

            - name: Prettier
              working-directory: ./
              run: npm prettier
